### ISSUE TITLE
Add Medical and Technical Universities

### ISSUE THREAD

**Issue by zeroibis** [Wayzware/EducationBalancer#5]
Please add support to add more capacity to the Medical and Technical Universities.

**Comment by Wayzware** [comment]
Hello,

This should already be possible by modifying the values in the config file located at: `C:\Users\YOUR_USERNAME_HERE\AppData\LocalLow\Colossal Order\Cities Skylines II\ModSettings\SchoolCapacityBalancer_Wayz`

Please let me know if have any other questions. I apologize for not responding to your previous issue post.

**Comment by zeroibis** [comment]
Oh no problem, I am sorry I closed my other issue once I realized there was a config file already so that was my fault for not reading everything.

For me the config file did not contain the options to adjust for the Medical and Technical Universities.

Now reading SchoolCapacityBalancerOptions.cs I can see:  "TechnicalUniversity01", "TechnicalUniversity01 Extension Wing",  "MedicalUniversity01", "MedicalUniversity01 Extension Wing" so I guess I just need to add those.

If you check under: `public static SchoolCapacityBalancerOptions`
you will see that by default the options to adjust the Medical and Technical Universities are not being added to default so that may be something worth adding to the auto config in the future. 

I will likely try this out in another week. I had installed the mod yesterday but I was working on a tram line and once I unpaused the game it would crash. It unfortunately kept crashing even after removing the mod and I had to revert to my last save before I installed the mod. I was working for a few hours with the game paused so I am not 100% sure it is actually an issue with the mod yet for now I am not going to load it until I have some time later next week. (Just FYI)

**Comment by Wayzware** [comment]
Ah, it looks like there is only logic to add the other schools to the config file when updating from the old version. I will update the mod soon to add these values to newly generated config files (such as yours). Thanks for bringing this to my attention.

As for the mod breaking your game, it is highly unlikely that my mod was the cause of that crash. Since my mod injects itself and makes all changes during game loading, we should see any errors at that point, so any crashes occurring after load is likely due to a different mod.

**Comment by Wayzware** [comment]
The mod has been updated and released on Paradox Mods. You are now able to change the capacity of all school buildings, though now at the education-level granularity instead of per school building.
